# -*- mode: ruby -*-
# vi: set ft=ruby :

#задаём переменные с количеством машин

$dev_mach = 3
$db_mach = 2
$test_mach = 1

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false

   (1..$dev_mach).each do |i|
        config.vm.define "dev-#{i}" do |dev|
         dev.vm.network  "public_network", ip: "192.168.1.#{10+i}"
         dev.vm.hostname = "dev-#{i}"
         dev.vm.provider "virtualbox" do |vb|
                vb.memory = "4096"
         end
         end
   end

   (1..$db_mach).each do |i|
        config.vm.define "db-#{i}" do |db|
         db.vm.network "public_network", ip: "192.168.1.#{50+i}"
         db.vm.hostname = "db-#{i}"
         db.vm.provider "virtualbox" do |vb|
                vb.memory = "2048"
        end
        end
   end

    (1..$test_mach).each do |i|
         config.vm.define "test-#{i}" do |test|
#          test.vm.network "public_network", type: "dhcp"
          test.vm.network "public_network", ip: "192.168.1.#{10+i}"
          test.vm.hostname = "test-#{i}"
          test.vm.provider "virtualbox" do |vb|
                 vb.memory = "1024"
         end
         end
    end
    config.vm.provision "shell", path: "script/AddUserAndKey.sh"
end