# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false

  config.vm.define "back" do |dev|
      dev.vm.network  "public_network", ip: "192.168.1.160"
      dev.vm.hostname = "back"
      dev.vm.provider "virtualbox" do |vb|
         vb.memory = "4096"
         vb.cpus=1
      end
  config.vm.provision "shell", path: "script/AddUserAndKey.sh"
  end

 config.vm.define "db" do |db|
     db.vm.network "public_network", ip: "192.168.1.161"
     db.vm.hostname = "db"  
     db.vm.provider "virtualbox" do |vb|
         vb.memory = "1024"
         vb.cpus=1
     end
 config.vm.provision "shell", path: "script/AddUserAndKey.sh"
 end

 config.vm.define "front" do |ci|
     ci.vm.network "public_network", ip: "192.168.1.162"
     ci.vm.hostname = "front"
     ci.vm.provider "virtualbox" do |vb|
         vb.memory = "2048"
         vb.cpus=1
     end
 config.vm.provision "shell", path: "script/AddUserAndKey.sh"
 end
end